language: r
sudo: false
latex: false
pandoc: false
cache: packages
r_github_packages:
- cran/yaml
- yufree/scifetch
- rstudio/blogdown
before_install:
- export TZ=Etc/GMT+12
- date
- git config --global user.email "yufree@live.cn"
- git config --global user.name "yufree"
script:
- Rscript R/fetch.R
after_success:
- git add --all *
- git commit -m "Daily update"
- git push -q https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master
env:
  global:
  - secure: JtnBJyUb2gNGpf/1FxQXjXSAuiqAyf0t1yGlAxWSsVtkYvH7AQbkv8mkBTKEcONA72J7foNF0nT5tJa8X3TIIyMqVEFWAoFjvHQzoCAzJ3S5pEsBJeDUWiv5nxGMYCreA+YjUuXS6hwLFWkmUDaYKrY0URbqc4KuvtWdEwsSF+Zbcu8aNBIMQtin6tcwB37SZAbL8/DJHzKxnOncJUTGpEwBkT8wcOc6hWv0Bh8nCqyEprTfKHY4JBdE6fA6TpMAok3ad8fIKtZSJK3S2jzVxGDihC4SgVb/SMw4uRMgypoha1q0yO+Q2e8rQTGQnz3sth+G6tNfQi1z+ArgkaDJ5NaMakJBmcqKOyqWTtLzQfQfCWeh8YvAKgwX2egqt8GWCrJzqCw4LYKgE6c4tc2X1cNnAZEIXVh6LEjT7F8o0huT0rlkBPNuN2SCn6/i2yeJ8Uw+YAJL2D4c2885pT2D/cGXXmE976ezV9wJnDBlot06HN6Pgsfy5ySp30EIOF38StkuF8T7uT/NeD9rkTdAX6+NFx8vCwc8pctMyeiiabeUGm7Lh5t5+IO0YHVnmt3NA34x0MNEYYlM8JeygqGOS2Uwz4q++tJ/YxsoA+mSDE7icaBlIeDrOaTWItTITGLznWwiS8H2aly/b8WYWT2WXarmYGrAXbvCC9VCPMoY95Y=
