language: r
sudo: false
latex: false
pandoc: false
cache: packages
r_github_packages:
- cran/yaml
- yufree/scifetch
- rstudio/blogdown
before_install:
- export TZ=Etc/GMT+12
- date
- git config --global user.email "yufree@live.cn"
- git config --global user.name "yufree"
script:
- Rscript R/fetch.R
after_success:
- git add --all *
- git commit -m "Daily update"
- git push -q https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master
env:
  global:
    secure: ex4U3vfeezGa1qmhNkYND3TVCLu/1JgjsjCVzgiFqo3eemRMWch8UMaDow9vTnlD50GjxA1H0SPazQMZTfIqkyqVoJZkGfTeGaJ/rtl2h8Ovf8M0x3BKGZHmUhsECPhSVpOK6Mlu6/OsxabCIjo2vnD5HIAq2Bu3pseHrbTJ1XRWrTmgBN1ZxONZ5zecNGKJxz2oezIZEiVLPLzbytVjU+b/WcRgAZXdhBIlT9gnFWKRllGCDJJlnsbtFRlEerHw97fnsMDw7E7SWT+6d34krwh1pnH+ZvJmLcCX2g9Lrq4cP6NCxTuVuiusBqvZONKvfAjZGdUXVqvZjO37OLEF3uP7RdVw3tk52sZHLrXdcHqAUEmBgzah4gPrGywWtN21JeucVKUREj29k/mGnzWeDpQdMUCYuZvxFFuJTmngivYLxYfMBXz/hFOEF1Rwz6U0nEgXtbC4jP6fOoFXr1amvaOD2a/ULayhAcn5UvqpztKv4N2y1qrYQjzKtBxX0YwYtMBBKCsl0F8ySYcLWjUJLTvEKYIvjZnqsn594HkqYD2EUEOlMDRGX4iOUN35ggAsiSzeEHTdRZLRbGa4O2S1bwItCvgMPWxgJpz7sinsNJ+ZYJMlCHQKRS0RpRNlXvIWNMB1vjhxznGtmLpfbmOTxkahIIXTPLA94qKc5brgREg=
