baseurl = "/"
languageCode = "en-us"
title = "Daily Environmental Research"
theme = "hugo-xmag"
googleAnalytics = "UA-74383918-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 9

[gitment]
  enable = true
  owner = 'yufree'
  repo = 'daily'
  client_id = 'cb0273f37b951850cb36' # Client ID
  client_secret = '89778cf8e7774bbfa19d6c882127dc2cd42876ad' # Client secret

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "News/Blog aggregator website for Enviromental Sciences"
    summary_length = 300
    github_edit = "https://github.com/yufree/enviRSS/edit/master/content/"
    footer = "&copy; [Miao YU](https://yufree.cn) 2018 | [Github](https://github.com/yufree) | [Twitter](https://twitter.com/yu_free)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
